# Generated by Django 6.0.7 on 2026-08-06 04:19

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_id', models.CharField(blank=True, max_length=20, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('captain', models.CharField(max_length=120)),
                ('captain_mobile', models.CharField(max_length=20)),
                ('alternate_mobile', models.CharField(blank=True, max_length=20)),
                ('district', models.CharField(max_length=100)),
                ('players', models.PositiveIntegerField(default=1)),
                ('jersey_color', models.CharField(blank=True, max_length=40)),
                ('payment_status', models.CharField(choices=[('Paid', 'Paid'), ('Pending', 'Pending')], default='Pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('date', models.DateField()),
                ('mode', models.CharField(choices=[('Cash', 'Cash'), ('UPI', 'UPI'), ('Card', 'Card'), ('Bank Transfer', 'Bank Transfer'), ('Online', 'Online')], max_length=20)),
                ('transaction_id', models.CharField(blank=True, max_length=100)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='tournaments.team')),
            ],
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('sport', models.CharField(choices=[('Football', 'Football'), ('Cricket', 'Cricket'), ('Futsal', 'Futsal'), ('Volleyball', 'Volleyball'), ('Custom', 'Custom')], max_length=20)),
                ('banner', models.ImageField(blank=True, upload_to='tournaments/')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('registration_deadline', models.DateField()),
                ('venue', models.CharField(max_length=180)),
                ('description', models.TextField(blank=True)),
                ('max_teams', models.PositiveIntegerField(default=8)),
                ('entry_fee', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('prize_1', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('prize_2', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('prize_3', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('organizer', models.CharField(max_length=120)),
                ('contact', models.CharField(max_length=20)),
                ('rules', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Registration Open', 'Registration Open'), ('Registration Closed', 'Registration Closed'), ('Live', 'Live'), ('Completed', 'Completed')], db_index=True, default='Draft', max_length=25)),
                ('format', models.CharField(choices=[('single', 'Single Elimination'), ('league', 'League')], default='single', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournaments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-start_date', 'name'],
            },
        ),
        migrations.AddField(
            model_name='team',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='tournaments.tournament'),
        ),
        migrations.CreateModel(
            name='Standing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('played', models.PositiveIntegerField(default=0)),
                ('won', models.PositiveIntegerField(default=0)),
                ('lost', models.PositiveIntegerField(default=0)),
                ('drawn', models.PositiveIntegerField(default=0)),
                ('goals_for', models.PositiveIntegerField(default=0)),
                ('goals_against', models.PositiveIntegerField(default=0)),
                ('points', models.PositiveIntegerField(default=0)),
                ('team', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='standing', to='tournaments.team')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standings', to='tournaments.tournament')),
            ],
            options={
                'ordering': ['-points', '-goals_for', 'team__name'],
            },
        ),
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('Registration Closing', 'Registration Closing'), ('Match Reminder', 'Match Reminder'), ('Final Match Reminder', 'Final Match Reminder'), ('Prize Distribution Reminder', 'Prize Distribution Reminder')], max_length=30)),
                ('due_at', models.DateTimeField()),
                ('is_done', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='tournaments.tournament')),
            ],
        ),
        migrations.CreateModel(
            name='Prize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('Champion', 'Champion'), ('Runner Up', 'Runner Up'), ('Second Runner', 'Second Runner'), ('MVP', 'MVP'), ('Best Goalkeeper', 'Best Goalkeeper'), ('Top Scorer', 'Top Scorer')], max_length=30)),
                ('recipient', models.CharField(blank=True, max_length=120)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('paid', models.BooleanField(default=False)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prizes', to='tournaments.tournament')),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('round', models.CharField(blank=True, max_length=40)),
                ('date', models.DateField(blank=True, null=True)),
                ('time', models.TimeField(blank=True, null=True)),
                ('ground', models.CharField(blank=True, max_length=100)),
                ('referee', models.CharField(blank=True, max_length=120)),
                ('score_a', models.PositiveIntegerField(default=0)),
                ('score_b', models.PositiveIntegerField(default=0)),
                ('wickets_a', models.PositiveIntegerField(default=0)),
                ('wickets_b', models.PositiveIntegerField(default=0)),
                ('overs_a', models.DecimalField(decimal_places=1, default=0, max_digits=4)),
                ('overs_b', models.DecimalField(decimal_places=1, default=0, max_digits=4)),
                ('status', models.CharField(choices=[('Upcoming', 'Upcoming'), ('Live', 'Live'), ('Completed', 'Completed')], default='Upcoming', max_length=12)),
                ('next_slot', models.CharField(blank=True, max_length=1)),
                ('next_match', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feeders', to='tournaments.match')),
                ('team_a', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches_a', to='tournaments.team')),
                ('team_b', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches_b', to='tournaments.team')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wins', to='tournaments.team')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='tournaments.tournament')),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('Sponsor', 'Sponsor'), ('Other', 'Other')], max_length=20)),
                ('source', models.CharField(max_length=120)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date', models.DateField()),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incomes', to='tournaments.tournament')),
            ],
        ),
        migrations.CreateModel(
            name='TournamentExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Ground Decoration', 'Ground Decoration'), ('Referee', 'Referee'), ('Water', 'Water'), ('Food', 'Food'), ('Marketing', 'Marketing'), ('Sound System', 'Sound System'), ('Electricity', 'Electricity'), ('Photography', 'Photography'), ('Other', 'Other')], max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='tournaments.tournament')),
            ],
        ),
        migrations.AddConstraint(
            model_name='team',
            constraint=models.UniqueConstraint(fields=('tournament', 'name'), name='unique_tournament_team'),
        ),
        migrations.AddConstraint(
            model_name='match',
            constraint=models.UniqueConstraint(fields=('tournament', 'number'), name='unique_tournament_match'),
        ),
    ]
