# Generated by Django 6.0.7 on 2026-08-05 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='googleuserprofile',
            options={'verbose_name': 'Google user', 'verbose_name_plural': 'Google users'},
        ),
    ]
