# Generated by Django 6.0.7 on 2026-09-02 07:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_set_production_site'),
        ('tournaments', '0002_tournament_registration_token'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='googleuserprofile',
            name='role',
            field=models.CharField(blank=True, choices=[('player', 'Player'), ('owner', 'Owner')], default='', max_length=20),
        ),
        migrations.CreateModel(
            name='PlayerPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='posts/')),
                ('video', models.FileField(blank=True, upload_to='posts/')),
                ('caption', models.TextField(max_length=1000)),
                ('sport', models.CharField(default='Cricket', max_length=30)),
                ('turf_tag', models.CharField(blank=True, max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sports_posts', to=settings.AUTH_USER_MODEL)),
                ('tournament', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='player_posts', to='tournaments.tournament')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, upload_to='players/')),
                ('mobile_number', models.CharField(max_length=20)),
                ('location', models.CharField(db_index=True, max_length=120)),
                ('sport', models.CharField(choices=[('Cricket', 'Cricket'), ('Football', 'Football'), ('Futsal', 'Futsal'), ('Volleyball', 'Volleyball')], default='Cricket', max_length=30)),
                ('position', models.CharField(max_length=100)),
                ('skill_level', models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced'), ('Professional', 'Professional')], max_length=30)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('bio', models.TextField(blank=True)),
                ('favourite_team', models.CharField(blank=True, max_length=120)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='player_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CricketScorecard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('runs', models.PositiveIntegerField(default=0)),
                ('balls', models.PositiveIntegerField(default=0)),
                ('fours', models.PositiveIntegerField(default=0)),
                ('sixes', models.PositiveIntegerField(default=0)),
                ('wickets', models.PositiveIntegerField(default=0)),
                ('overs', models.DecimalField(decimal_places=1, default=0, max_digits=4)),
                ('runs_conceded', models.PositiveIntegerField(default=0)),
                ('catches', models.PositiveIntegerField(default=0)),
                ('dismissal', models.CharField(blank=True, max_length=180)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cricket_scorecards', to='tournaments.match')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cricket_scorecards', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scorecards', to='tournaments.team')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('match', 'player'), name='unique_match_player_scorecard')],
            },
        ),
        migrations.CreateModel(
            name='PlayerTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_memberships', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_memberships', to='tournaments.team')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('player', 'team'), name='unique_player_team')],
            },
        ),
    ]
