# Generated by Django 6.0.7 on 2026-09-05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_playermatchrecord_player_performance_fields"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="cricketscorecard",
            name="unique_match_player_scorecard",
        ),
        migrations.RemoveField(model_name="playermatchrecord", name="player"),
        migrations.RemoveField(model_name="playermatchrecord", name="tournament"),
        migrations.RemoveField(model_name="playerpost", name="player"),
        migrations.RemoveField(model_name="playerpost", name="tournament"),
        migrations.RemoveField(model_name="playerprofile", name="user"),
        migrations.RemoveConstraint(
            model_name="playerteam",
            name="unique_player_team",
        ),
        migrations.RemoveField(model_name="googleuserprofile", name="role"),
        migrations.RemoveField(model_name="cricketscorecard", name="match"),
        migrations.RemoveField(model_name="cricketscorecard", name="player"),
        migrations.RemoveField(model_name="cricketscorecard", name="team"),
        migrations.DeleteModel(name="PlayerMatchRecord"),
        migrations.DeleteModel(name="PlayerPost"),
        migrations.DeleteModel(name="PlayerProfile"),
        migrations.RemoveField(model_name="playerteam", name="player"),
        migrations.RemoveField(model_name="playerteam", name="team"),
        migrations.DeleteModel(name="CricketScorecard"),
        migrations.DeleteModel(name="PlayerTeam"),
    ]
