# Generated by Django 6.0.7 on 2026-08-03 15:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(default='My Turf', max_length=120)),
                ('logo', models.ImageField(blank=True, upload_to='logos/')),
                ('currency', models.CharField(choices=[('₹', 'INR (₹)'), ('$', 'USD ($)'), ('€', 'EUR (€)'), ('£', 'GBP (£)')], default='₹', max_length=3)),
                ('timezone', models.CharField(default='Asia/Kolkata', max_length=60)),
                ('opening_time', models.TimeField(default='06:00')),
                ('closing_time', models.TimeField(default='23:00')),
                ('monthly_revenue_goal', models.DecimalField(decimal_places=2, default=100000, max_digits=12)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='business_settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
