# Generated by Django 6.0.7 on 2026-08-03 15:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesssettings',
            name='closing_time',
            field=models.TimeField(default=datetime.time(23, 0)),
        ),
        migrations.AlterField(
            model_name='businesssettings',
            name='opening_time',
            field=models.TimeField(default=datetime.time(6, 0)),
        ),
    ]
