# Generated by Django 6.0.7 on 2026-08-04 05:33

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('business', '0002_alter_businesssettings_closing_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TurfOwnerWorkspace',
            fields=[
            ],
            options={
                'verbose_name': 'Turf owner folder',
                'verbose_name_plural': 'Turf owner folders',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
