# Generated by Django 6.0.7 on 2026-08-19 04:45

from django.db import migrations, models


def mark_existing_profiles_complete(apps, schema_editor):
    apps.get_model("business", "BusinessSettings").objects.update(onboarding_completed=True)


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0005_ground_operating_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesssettings',
            name='onboarding_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(mark_existing_profiles_complete, migrations.RunPython.noop),
    ]
