# Generated by Django 6.0.7 on 2026-08-04 06:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(max_length=100, unique=True)),
                ('event_type', models.CharField(max_length=80)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razorpay_subscription_id', models.CharField(blank=True, max_length=80, null=True, unique=True)),
                ('razorpay_payment_id', models.CharField(blank=True, max_length=80)),
                ('razorpay_plan_id', models.CharField(blank=True, max_length=80)),
                ('status', models.CharField(db_index=True, default='created', max_length=30)),
                ('current_start', models.DateTimeField(blank=True, null=True)),
                ('current_end', models.DateTimeField(blank=True, null=True)),
                ('cancel_at_cycle_end', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='premium_subscription', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
