# Generated by Django 6.0.7 on 2026-08-04 06:24

import django.utils.timezone
import subscriptions.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='trial_end',
            field=models.DateTimeField(default=subscriptions.models.default_trial_end),
        ),
        migrations.AddField(
            model_name='subscription',
            name='trial_start',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='status',
            field=models.CharField(db_index=True, default='trialing', max_length=30),
        ),
    ]
