# Generated by Django 6.0.7 on 2026-08-19 05:01

import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


def merge_duplicate_customers(apps, schema_editor):
    Customer = apps.get_model("bookings", "Customer")
    Booking = apps.get_model("bookings", "Booking")
    for owner_id in Customer.objects.values_list("owner_id", flat=True).distinct():
        canonical_by_name = {}
        for customer in Customer.objects.filter(owner_id=owner_id).order_by("id"):
            key = customer.name.strip().casefold()
            canonical = canonical_by_name.get(key)
            if canonical is None:
                canonical_by_name[key] = customer
                clean_name = customer.name.strip()
                if clean_name != customer.name:
                    customer.name = clean_name
                    customer.save(update_fields=("name",))
                continue
            Booking.objects.filter(customer_id=customer.pk).update(customer_id=canonical.pk)
            duplicate_phone = customer.phone
            duplicate_email = customer.email
            customer.delete()
            changed = []
            if not canonical.phone and duplicate_phone:
                canonical.phone = duplicate_phone
                changed.append("phone")
            if not canonical.email and duplicate_email:
                canonical.email = duplicate_email
                changed.append("email")
            if changed:
                canonical.save(update_fields=changed)


class Migration(migrations.Migration):

    # PostgreSQL must commit the Booking FK updates from the data migration
    # before it can create a new index on the referenced Customer table.
    atomic = False

    dependencies = [
        ('bookings', '0004_remove_customer_unique_owner_customer_phone_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(merge_duplicate_customers, migrations.RunPython.noop, atomic=True),
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower(django.db.models.functions.text.Trim('name')), models.F('owner'), name='unique_owner_customer_name_ci'),
        ),
    ]
